name: Django CI/CD

on:
  push:
    branches: [ "master" ]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - name: Create variables
        id: vars
        run: |
          BRANCH=$(echo ${GITHUB_REF##*/} | tr a-z A-Z)
          echo "::set-output name=PATH_PROJECT::PATH_PROJECT_$BRANCH"
          echo "::set-output name=SSH_HOST::SSH_HOST_$BRANCH"
          echo "::set-output name=SSH_PASSWORD::SSH_PASSWORD_$BRANCH"
          echo "::set-output name=SSH_USERNAME::SSH_USERNAME_$BRANCH"
          echo "::set-output name=SSH_PORT::SSH_PORT_$BRANCH"
          echo "::set-output name=BRANCH::$BRANCH"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[steps.vars.outputs.SSH_HOST] }}
          port: ${{ secrets[steps.vars.outputs.SSH_PORT] }}
          password: ${{ secrets[steps.vars.outputs.SSH_PASSWORD] }}
          username: ${{ secrets[steps.vars.outputs.SSH_USERNAME] }}
          script: |
            cd ${{ secrets[steps.vars.outputs.PATH_PROJECT] }}
            git reset --hard
            git pull
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          script: echo hello world > hello.txt
      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[steps.vars.outputs.SSH_HOST] }}
          port: ${{ secrets[steps.vars.outputs.SSH_PORT] }}
          password: ${{ secrets[steps.vars.outputs.SSH_PASSWORD] }}
          username: ${{ secrets[steps.vars.outputs.SSH_USERNAME] }}
          script: |
            cd ${{ secrets[steps.vars.outputs.PATH_PROJECT] }}
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install virtualenv
            python3 -m venv env
      - name: Runserver
        env:
          DJANGO_SETTINGS_MODULE: orthodoxkoln.settings
        run: python orthodoxkoln/manage.py runserver
